theme: jekyll-theme-minimal
title: Camille Marchet
description: I'm a postdoc researcher with Rayan Chikhi and Mikaël Salson in BONSAI team (CRISTAL, CNRS, Univ Lille)
logo: IMG_20190219_142939.jpg
show_downloads: true
