theme: jekyll-theme-minimal
title: Camille Marchet
description: I'm a postdoc researcher with [Rayan Chikhi](http://rayan.chikhi.name/) and [Mikaël Salson](https://mikael-salson.univ-lille.fr/) in [BONSAI team](https://www.cristal.univ-lille.fr/bonsai/) ([CRISTAL](https://www.cristal.univ-lille.fr/), CNRS, Univ Lille)
logo: IMG_20190219_142939.jpg
show_downloads: true
